AXINR	; REBUILDS ^AXINR
	; ^AXINR HELPS KILL ENTIRES FROM ^AXIN, RATHER THAN RELYING ON ^TCODES($JOB)
	QUIT

N	;
	SET (VALPROP,VALUE,CODE,ID)=""
	F  S VALPROP=$O(^AXIN(VALPROP)) Q:VALPROP=""  D
	.F  S VALUE=$O(^AXIN(VALPROP,"N",VALUE)) Q:VALUE=""  D
	..F  S CODE=$O(^AXIN(VALPROP,"N",VALUE,CODE)) Q:CODE=""  D
	...F  S ID=$O(^AXIN(VALPROP,"N",VALUE,CODE,ID)) Q:ID=""  D
	....S ^AXINR(ID,"N",CODE,VALUE,VALPROP)=""
	QUIT
X	;
	SET (CODEPROP,CODE,ID)=""
	F  S CODEPROP=$O(^AXIN(CODEPROP)) Q:CODEPROP=""  D
	.F  S CODE=$O(^AXIN(CODEPROP,"X",CODE)) Q:CODE=""  D
	..F  S ID=$O(^AXIN(CODEPROP,"X",CODE,ID)) Q:ID=""  D
	...S ^AXINR(ID,"X",CODE,CODEPROP)=""
	QUIT